<?php

namespace UMRA\Bundle\MemberBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransRepository extends EntityRepository
{
    public function queryAll()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return $qb
            ->select('t')
            ->from('UMRAMemberBundle:Trans', 't')
            ->orderBy('t.id', 'DESC')
            ->getQuery();
    }

    public function findLatestLuncheonFees($person, $count = 10)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return $qb
            ->select('t')
            ->from('UMRAMemberBundle:Trans', 't')
            ->where("t.trantype = 'LUNCHEON_FEE'")
            ->andWhere('t.person = :personId')
            ->setParameter('personId', $person->getId())
            ->orderBy('t.id', 'DESC')
            ->setMaxResults((int) $count)
            ->getQuery()
            ->getResult();
    }

    public function findLatestMembershipFees($person, $count = 10)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return $qb
            ->select('t')
            ->from('UMRAMemberBundle:Trans', 't')
            ->where($qb->expr()->orX(
                    $qb->expr()->eq('t.trantype', "'MEMBERSHIP_NEW'"),
                    $qb->expr()->eq('t.trantype', "'MEMBERSHIP_RENEW'")
            ))
            ->andWhere('t.person = :personId')
            ->setParameter('personId', $person->getId())
            ->orderBy('t.id', 'DESC')
            ->setMaxResults((int) $count)
            ->getQuery()
            ->getResult();
    }

    public function findLatestVerifiedMemberFee($person)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return $qb
            ->select('t')
            ->from('UMRAMemberBundle:Trans', 't')
            ->where($qb->expr()->orX(
                    $qb->expr()->eq('t.trantype', "'MEMBERSHIP_NEW'"),
                    $qb->expr()->eq('t.trantype', "'MEMBERSHIP_RENEW'")
            ))
            ->andWhere("t.status = 'PROCESSED'")
            ->andWhere('t.person = :personId')
            ->setParameter('personId', $person->getId())
            ->orderBy('t.reconciledDate', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
