UMRA_Landing:
    pattern:  /
    defaults: { _controller: UMRAMemberBundle:Default:index }
    methods: [GET]
UMRA_Email_show:
    pattern:  /email/{id}
    defaults: { _controller: UMRAMemberBundle:Email:show }
    methods: [GET]
UMRA_Email_edit:
    pattern:  /email/{id}/edit
    defaults: { _controller: UMRAMemberBundle:Email:edit }
    methods: [GET]
UMRA_Email_update:
    pattern:  /email/{id}
    defaults: { _controller: UMRAMemberBundle:Email:update }
    methods: [PUT]
UMRA_Email_delete:
    pattern: /email/{id}
    defaults: { _controller: UMRAMemberBundle:Email:delete }
    methods: [DELETE]
UMRA_Household:
    pattern:  /households
    defaults: { _controller: UMRAMemberBundle:Household:index }
    methods: [GET]
UMRA_Household_new:
    pattern:  /household/new
    defaults: { _controller: UMRAMemberBundle:Household:new }
    methods: [GET]
UMRA_Household_show:
    pattern:  /household/{id}
    defaults: { _controller: UMRAMemberBundle:Household:show }
    methods: [GET]
UMRA_Household_edit:
    pattern:  /household/{id}/edit
    defaults: { _controller: UMRAMemberBundle:Household:edit }
    methods: [GET]
UMRA_Household_Person_new:
    pattern:  /household/{householdId}/person/new
    defaults: { _controller: UMRAMemberBundle:Person:new }
    methods: [GET]
UMRA_Household_Person_create:
    pattern: /household/{householdId}/person
    defaults: { _controller: UMRAMemberBundle:Person:create }
    methods: [POST]
UMRA_Household_Residence_new:
    pattern:  /household/{householdId}/residence/new
    defaults: { _controller: UMRAMemberBundle:Residence:new }
    methods: [GET]
UMRA_Household_Residence_create:
    pattern: /household/{householdId}/residence
    defaults: { _controller: UMRAMemberBundle:Residence:create }
    methods: [POST]
UMRA_Household_Email_new:
    pattern:  /household/{householdId}/email/new
    defaults: { _controller: UMRAMemberBundle:Email:new, personId: ~ }
    methods: [GET]
UMRA_Household_Email_create:
    pattern: /household/{householdId}/email
    defaults: { _controller: UMRAMemberBundle:Email:create, personId: ~ }
    methods: [POST]
UMRA_Household_update:
    pattern:  /household/{id}
    defaults: { _controller: UMRAMemberBundle:Household:update }
    methods: [PUT]
UMRA_Household_create:
    pattern: /household
    defaults: { _controller: UMRAMemberBundle:Household:create }
    methods: [POST]
UMRA_Household_delete:
    pattern:  /household/{id}
    defaults: { _controller: UMRAMemberBundle:Household:delete }
    methods: [DELETE]
UMRA_Person:
    pattern:  /persons
    defaults: { _controller: UMRAMemberBundle:Person:index, _format: json }
    methods: [GET]
UMRA_Person_Email_new:
    pattern:  /person/{personId}/email/new
    defaults: { _controller: UMRAMemberBundle:Email:new }
    methods: [GET]
UMRA_Person_Email_create:
    pattern: /person/{personId}/email
    defaults: { _controller: UMRAMemberBundle:Email:create }
    methods: [POST]
UMRA_Person_Phone_new:
    pattern:  /person/{personId}/phone/new
    defaults: { _controller: UMRAMemberBundle:Phone:new }
    methods: [GET]
UMRA_Person_Phone_create:
    pattern:  /person/{personId}/phone
    defaults: { _controller: UMRAMemberBundle:Phone:create }
    methods: [POST]
UMRA_Person_show:
    pattern:  /person/{id}
    defaults: { _controller: UMRAMemberBundle:Person:show }
    methods: [GET]
UMRA_Person_edit:
    pattern:  /person/{id}/edit
    defaults: { _controller: UMRAMemberBundle:Person:edit }
    methods: [GET]
UMRA_Person_update:
    pattern:  /person/{id}
    defaults: { _controller: UMRAMemberBundle:Person:update }
    methods: [PUT]
UMRA_Person_delete:
    pattern: /person/{id}
    defaults: { _controller: UMRAMemberBundle:Person:delete }
    methods: [DELETE]
UMRA_Person_Profile:
    pattern:  /profile
    defaults: { _controller: UMRAMemberBundle:Person:profile }
    methods: [GET]
UMRA_Phone:
    pattern:  /phones
    defaults: { _controller: UMRAMemberBundle:Phone:index }
    methods: [GET]
UMRA_Phone_show:
    pattern:  /phone/{id}
    defaults: { _controller: UMRAMemberBundle:Phone:show }
    methods: [GET]
UMRA_Phone_edit:
    pattern:  /phone/{id}/edit
    defaults: { _controller: UMRAMemberBundle:Phone:edit }
    methods: [GET]
UMRA_Phone_update:
    pattern:  /phone/{id}
    defaults: { _controller: UMRAMemberBundle:Phone:update }
    methods: [PUT]
UMRA_Phone_create:
    pattern: /phone
    defaults: { _controller: UMRAMemberBundle:Phone:create }
    methods: [POST]
UMRA_Phone_delete:
    pattern: /phone/{id}
    defaults: { _controller: UMRAMemberBundle:Phone:delete }
    methods: [DELETE]
UMRA_Residence:
    pattern:  /residences
    defaults: { _controller: UMRAMemberBundle:Residence:index }
    methods: [GET]
UMRA_Residence_Phone_new:
    pattern:  /residence/{residenceId}/phone/new
    defaults: { _controller: UMRAMemberBundle:Phone:new, personId: ~ }
    methods: [GET]
UMRA_Residence_Phone_create:
    pattern: /residence/{residenceId}/phone
    defaults: { _controller: UMRAMemberBundle:Phone:create, personId: ~ }
    methods: [POST]
UMRA_Residence_show:
    pattern:  /residence/{id}
    defaults: { _controller: UMRAMemberBundle:Residence:show }
    methods: [GET]
UMRA_Residence_edit:
    pattern:  /residence/{id}/edit
    defaults: { _controller: UMRAMemberBundle:Residence:edit }
    methods: [GET]
UMRA_Residence_update:
    pattern:  /residence/{id}
    defaults: { _controller: UMRAMemberBundle:Residence:update }
    methods: [PUT]
UMRA_Residence_delete:
    pattern: /residence/{id}
    defaults: { _controller: UMRAMemberBundle:Residence:delete }
    methods: [DELETE]
UMRA_Role:
    pattern:  /roles
    defaults: { _controller: UMRAMemberBundle:Role:index }
    methods: [GET]
UMRA_Role_new:
    pattern:  /role/new
    defaults: { _controller: UMRAMemberBundle:Role:new }
    methods: [GET]
UMRA_Role_show:
    pattern:  /role/{id}
    defaults: { _controller: UMRAMemberBundle:Role:show }
    methods: [GET]
UMRA_Role_edit:
    pattern:  /role/{id}/edit
    defaults: { _controller: UMRAMemberBundle:Role:edit }
    methods: [GET]
UMRA_Role_update:
    pattern:  /role/{id}
    defaults: { _controller: UMRAMemberBundle:Role:update }
    methods: [PUT]
UMRA_Role_create:
    pattern: /role
    defaults: { _controller: UMRAMemberBundle:Role:create }
    methods: [POST]
UMRA_Role_delete:
    pattern: /role/{id}
    defaults: { _controller: UMRAMemberBundle:Role:delete }
    methods: [DELETE]
UMRA_Trans_new:
    pattern:  /transaction/new
    defaults: { _controller: UMRAMemberBundle:Trans:new }
    methods: [GET]
UMRA_Trans:
    pattern:  /transactions
    defaults: { _controller: UMRAMemberBundle:Trans:index }
    methods: [GET]
UMRA_Trans_edit:
    pattern:  /transaction/{id}/edit
    defaults: { _controller: UMRAMemberBundle:Trans:edit }
    methods: [GET]
UMRA_Trans_show:
    pattern:  /transaction/{id}
    defaults: { _controller: UMRAMemberBundle:Trans:show }
    methods: [GET]
UMRA_Trans_update:
    pattern:  /transaction/{id}
    defaults: { _controller: UMRAMemberBundle:Trans:update }
    methods: [PUT]
UMRA_Trans_create:
    pattern: /transaction
    defaults: { _controller: UMRAMemberBundle:Trans:create }
    methods: [POST]
UMRA_Trans_delete:
    pattern: /transaction/{id}
    defaults: { _controller: UMRAMemberBundle:Trans:delete }
    methods: [DELETE]
UMRA_register:
    pattern: /register
    defaults: { _controller: UMRAMemberBundle:Registration:register }
    methods: [GET, POST]
UMRA_renew:
    pattern: /renew
    defaults: { _controller: UMRAMemberBundle:Registration:renew }
    methods: [GET, POST]
