parameters:
#    umra_member.example.class: UMRA\Bundle\MemberBundle\Example

services:
    umra_member.user_manipulator:
        class: UMRA\Bundle\MemberBundle\Services\UserManipulator
        arguments: ["@fos_user.user_manager"]
    umra_member.admin.household:
        class: UMRA\Bundle\MemberBundle\Admin\HouseholdAdmin
        arguments: [~, UMRA\Bundle\MemberBundle\Entity\Household, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "UMRA Membership", label: Household }

    umra_member.admin.member:
        class: UMRA\Bundle\MemberBundle\Admin\MemberAdmin
        arguments: [~, UMRA\Bundle\MemberBundle\Entity\Person, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "UMRA Membership", label: Member }

    umra_member.admin.residence:
        class: UMRA\Bundle\MemberBundle\Admin\ResidenceAdmin
        arguments: [~, UMRA\Bundle\MemberBundle\Entity\Residence, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "UMRA Membership", label: Residence}

    umra_member.admin.email:
        class: UMRA\Bundle\MemberBundle\Admin\EmailAdmin
        arguments: [~, UMRA\Bundle\MemberBundle\Entity\Email, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "UMRA Membership", label: Email}

    umra_member.admin.phone:
        class: UMRA\Bundle\MemberBundle\Admin\PhoneAdmin
        arguments: [~, UMRA\Bundle\MemberBundle\Entity\Phone, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "UMRA Membership", label: Phone}

    umra_member.admin.trans:
        class: UMRA\Bundle\MemberBundle\Admin\TransAdmin
        arguments: [~, UMRA\Bundle\MemberBundle\Entity\Trans, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: "UMRA Transactions", label: Transaction}

    umra_member.handlers.person_create:
        class: UMRA\Bundle\MemberBundle\Handlers\PersonCreateHandler
        arguments: ["@doctrine.orm.default_entity_manager", "@fos_user.user_manager", "@fos_user.util.token_generator", "@logger"]

    umra_member.handlers.membership_transaction_builder:
        class: UMRA\Bundle\MemberBundle\Handlers\MembershipTransactionBuilder
        arguments: [ @doctrine.orm.default_entity_manager ]

    umra_member.listeners.person_ensure_password:
        class: UMRA\Bundle\MemberBundle\EventListeners\PersonEnsurePasswordListener
        arguments: ["@logger"]
        tags:
            - { name: doctrine.event_subscriber, priority: 10 }

    umra_member.twig_extensions:
        class: UMRA\Bundle\MemberBundle\Services\TwigExtensions
        arguments: ["@doctrine.orm.default_entity_manager", "@logger"]
        public: false
        tags:
            - { name: twig.extension }
