parameters:
#    umra_member.example.class: UMRA\Bundle\MemberBundle\Example

services:
    umra_member.user_manipulator:
        class: UMRA\Bundle\MemberBundle\Services\UserManipulator
        arguments: ["@fos_user.user_manager"]
